# example: https://github.com/anolilab/workflows/blob/main/step/setup/action.yml
---
name: Download packages 'dist'
description: Download packages 'dist' artifacts from 'compile' job

runs:
  using: composite
  steps:

  - uses: actions/checkout@v6
    with:
      fetch-depth: 0

  - uses: ./.github/actions/setup
    with:
      node-version: "24.x"

  - uses: ./.github/actions/download-package-dist

  - name: Update API documentation
    shell: bash
    run: pnpm run --if-present build:readme:API

  - name: Update readme.md
    shell: bash
    run: pnpm run --if-present build:readme

  - uses: codfish/semantic-release-action@v4
    env:
      GIT_AUTHOR_NAME: "github-actions-shell"
      GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
      GIT_COMMITTER_NAME: "github-actions-shell"
      GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
