---
name: Test

on:
  workflow_call:
    inputs:
      badges-gist-id:
        required: false
        type: string
        description: gist id for badges publishing
        default: ${{ vars.BADGES_GIST_ID }}

jobs:
  test:
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    uses: IT-Service-NPM/.github/.github/workflows/test-only-package.yml@main
    secrets: inherit

  publish-test-results:
    name: Test results publishing
    needs:
      - test
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    uses: IT-Service-NPM/.github/.github/workflows/publish-package-test-result.yml@main
    with:
      badges-gist-id: ${{ inputs.badges-gist-id }}
    secrets: inherit
